WebsiteHaciendaCañaveralSolution/MVCEFHaciendaCañaveral/Models/Instruccion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCEFHaciendaCañaveral.Models
{
    public class Instruccion
    {
        [Key]
        public int IdInstruccion { get; set; }
        [Required]
        public String Descripcion { get; set; }
        [StringLength(255)]
        [Index("UQ_URLImagenInstruccion", IsUnique = true)]
        public String UrlImagen { get; set; }
        public int IdReceta { get; set; }
        [ForeignKey("IdReceta")]
        public Receta Receta { get; set; }
    }
}

WebsiteHaciendaCañaveralSolution/MVCEFHaciendaCañaveral/Controllers/InstruccionController.cs
using MVCEFHaciendaCañaveral.Business;
using MVCEFHaciendaCañaveral.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEFHaciendaCañaveral.Controllers
{
    public class InstruccionController : Controller
    {
        private InstruccionBusiness instruccionBusiness;
        private RecetaBusiness recetaBusiness;

        public InstruccionController()
        {
            this.instruccionBusiness = new InstruccionBusiness();
            this.recetaBusiness = new RecetaBusiness();
        }

        // GET: Instruccion
        public ActionResult Index()
        {
            var model = instruccionBusiness.GetAllInstrucciones();
            return View(model);
        }

        public ActionResult Preview(string file)
        {
            var path = ControllerContext.HttpContext.Server.MapPath("~/Images/Instrucciones/");
            if (System.IO.File.Exists(Path.Combine(path, file)))
            {
                return File(Path.Combine(path, file), "image/jpeg");
            }
            return new HttpNotFoundResult();
        }

        // GET: Instruccion/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Instruccion/Create
        public ActionResult Create()
        {
            ViewBag.Recetas = recetaBusiness.GetAllRecetaItem();
            return View();
        }

        // POST: Instruccion/Create
        [HttpPost]
        public ActionResult Create(Instruccion instruccion,HttpPostedFileBase file)
        {
            try
            {
                string ruta = Server.MapPath("~/Images/Instrucciones/");

                if (instruccionBusiness.Create(instruccion, file, ruta))
                {
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                
            }
            return View();
        }

        // GET: Instruccion/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Instruccion/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Instruccion/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Instruccion/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebsiteHaciendaCañaveralSolution/MVCEFHaciendaCañaveral/Views/Instruccion/Create.cshtml
@model MVCEFHaciendaCañaveral.Models.Instruccion

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Instruccion",FormMethod.Post, new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Instruccion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlImagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" placeholder="Seleccione una imagen" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdReceta, "IdReceta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdReceta", new SelectList(ViewBag.Recetas,"Value","Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdReceta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebsiteHaciendaCañaveralSolution/MVCEFHaciendaCañaveral/Views/Instruccion/Index.cshtml
@model IEnumerable<MVCEFHaciendaCañaveral.Models.Instruccion>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Receta.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Receta.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            <img src="@Url.Action("Preview", new {file=item.UrlImagen})" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdInstruccion }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdInstruccion }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdInstruccion })
        </td>
    </tr>
}

</table>