WebsiteHaciendaCañaveralSolution/MVCEFHaciendaCañaveral/Models/Ingrediente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCEFHaciendaCañaveral.Models
{
    public class Ingrediente
    {
        [Key]
        public int IdIngrediente { get; set; }
        [Required]
        public String Nombre { get; set; }
        [StringLength(255)]
        [Index("UQ_URLImagenIngrediente", IsUnique = true)]
        public String UrlImagen { get; set; }
        public int IdReceta { get; set; }
        [ForeignKey("IdReceta")]
        public Receta Receta { get; set; }
    }
}

WebsiteHaciendaCañaveralSolution/MVCEFHaciendaCañaveral/Controllers/IngredienteController.cs
using MVCEFHaciendaCañaveral.Business;
using MVCEFHaciendaCañaveral.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEFHaciendaCañaveral.Controllers
{
    public class IngredienteController : Controller
    {
        private IngredienteBusiness ingredienteBusiness;
        private RecetaBusiness recetaBusiness;

        public IngredienteController()
        {
            this.ingredienteBusiness = new IngredienteBusiness();
            this.recetaBusiness = new RecetaBusiness();
        }
        // GET: Ingrediente
        public ActionResult Index()
        {
            var model = ingredienteBusiness.GetAllIngredientes();
            return View(model);
        }

        public ActionResult Preview(string file)
        {
            var path = ControllerContext.HttpContext.Server.MapPath("~/Images/Ingredientes/");
            if (System.IO.File.Exists(Path.Combine(path, file)))
            {
                return File(Path.Combine(path, file), "image/jpeg");
            }
            return new HttpNotFoundResult();
        }


        // GET: Ingrediente/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Ingrediente/Create
        public ActionResult Create()
        {
            ViewBag.Recetas = recetaBusiness.GetAllRecetaItem();
            return View();
        }

        // POST: Ingrediente/Create
        [HttpPost]
        public ActionResult Create(Ingrediente ingrediente, HttpPostedFileBase file)
        {
            try
            {
                string ruta = Server.MapPath("~/Images/Ingredientes/");

                if (ingredienteBusiness.Create(ingrediente, file, ruta))
                {
                    Response.Write("<script language='JavaScript'>alert('Ingrediente registrado con exito');</script>");
                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }
            return View();
        }

        // GET: Ingrediente/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Ingrediente/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Ingrediente/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Ingrediente/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebsiteHaciendaCañaveralSolution/MVCEFHaciendaCañaveral/Views/Ingrediente/Create.cshtml
@model MVCEFHaciendaCañaveral.Models.Ingrediente

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>



@using (Html.BeginForm("Create", "Ingrediente", FormMethod.Post,new { enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingrediente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlImagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" placeholder="Seleccione una imagen" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdReceta, "IdReceta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdReceta", new SelectList(ViewBag.Recetas,"Value","Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdReceta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebsiteHaciendaCañaveralSolution/MVCEFHaciendaCañaveral/Views/Ingrediente/Index.cshtml
@model IEnumerable<MVCEFHaciendaCañaveral.Models.Ingrediente>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Receta.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayName("Imagen")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Receta.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            <img src="@Url.Action("Preview", new {file=item.UrlImagen})" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IdIngrediente }) |
            @Html.ActionLink("Details", "Details", new { id=item.IdIngrediente }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IdIngrediente })
        </td>
    </tr>
}

</table>